#!/bin/bash

# LD_PRELOAD
trace_so=palial_trace/libpalial_trace.so
omp_so=../llvm-project/build-openmp/lib/libomp.so

# Parameters
msize=(8192 16384 24576 32768)
bsize=512
algo=cholesky
max_th=(31 63)      # numactl
governor=userspace
target="syrk_trsm_to_min"

# Compile power control part
cd palial_power
gcc server.c -lzmq -lcpufreq -o palial_server
cd -

# Compile trace library part
cd palial_trace
make clean
make
cd -

# Compile source part
cd palial_src
make clean
make
cd -

for nth in ${max_th[*]}
do
    for matrix in ${msize[*]}
    do
        echo $nth $matrix
        export OMP_NUM_THREADS=$(expr $nth + 1)

        # Start server
        sudo palial_power/palial_server $(expr $nth + 1) $governor &
        
        # Launch runs
        LD_PRELOAD=$omp_so:$trace_so numactl --physcpubind=0-$nth palial_src/palial -a $algo -m $matrix -b $bsize >> tasks_times_${matrix}_${bsize}_${nth}_${governor}_$target
    done
done
